### ISSUE TITLE
When delivery method is changed to store pickup, select pickup location does not get enabled.

### ISSUE THREAD

**Issue by appurvajain** [hotwax/reroute-fulfilment#56]
When the delivery method is changed from shipping to store pickup, the button to select the pickup location remains disbaled.

![Screenshot 2023-03-28 at 10 58 28 AM](https://user-images.githubusercontent.com/113335194/228137085-4c3ca6ec-beee-4e20-9d97-a14f01f49b42.png)

**Comment by adityasharma7** [comment]
Done with https://github.com/hotwax/reroute-fulfilment/pull/57
