### ISSUE TITLE
Facilities(Stores) not showing up  even though inventory is available

### ISSUE THREAD

**Issue by Chinmay2107** [hotwax/reroute-fulfilment#85]
**Existing issue**
For orders with multiple items, The facilities are not shown up.
The API fetches the facilities and inventory lookup also has the result, but the store's list does not have any of the stores with the message "Stores not found".

**Steps to reproduce the issue:**
1) Place a BOPIS order on staging.
2) Go to the BOPIS app and reject the order.
3) Open the link received in the email for rerouting the order.
4) Click on "Select Pickup Location".
5) No stores will be displayed in the facilities list.

**Comment by dt2patel** [comment]
@Chinmay2107 please add a jam recording of this issue being re-produced so we can debug faster

**Comment by Chinmay2107** [comment]
@dt2patel @ravilodhi Sir,

I have reproduced the issue. But it does not exist now. I am able to get the facilities where the inventory is available for all the items. We can close this issue.

Earlier it could be happening either due to inventory was not available at the same location or the facility was not allowed for pickup.

**Comment by dt2patel** [comment]
Closing issue as suggested
