### ISSUE TITLE
Unable to Make Partial Changes to Saved Shipping Address

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/reroute-fulfilment#94]
## Steps to Reproduce
Open the re-route link.
Select delivery method as shipping.
Enter the address and save it.
Attempt to modify specific fields (e.g., street name, postal code) without re-entering the entire address using the edit address button option.
Observe the issue.

## Expected Behavior
Users should be able to modify specific fields within the saved address without the need to re-enter the entire address.

## Actual Behavior
Users are forced to re-enter the complete correct address and save it again to apply changes.

**Comment by dt2patel** [comment]
@Adameddy26 are you able to attach a jam video for this? I'd like to see the exact issue here. Since we are going to be updating this app soon, we can put this fix in as well.

**Comment by Adameddy26** [comment]
> @Adameddy26 are you able to attach a jam video for this? I'd like to see the exact issue here. Since we are going to be updating this app soon, we can put this fix in as well.

https://jam.dev/c/0deaa4fd-b3dd-4f55-9469-f390782873cc
Currently, when a user saves a shipping address and later opens the Edit Address modal, the previously saved address does not appear pre-filled in the fields. This forces the user to re-enter the entire address instead of making partial edits.
